[package]
name = "goblin-vm"
version = "0.1.0"
edition = "2021"

[dependencies]
slab = "0.4"
goblin-ast = { path = "../goblin-ast" }
goblin-diagnostics = { path = "../goblin-diagnostics" }
goblin-parser = { path = "../goblin-parser" }
goblin-lexer = { path = "../goblin-lexer" }
rust_decimal = "1"
indexmap = "2"
regex = "1"
serde_json = "1"
