[package]
name = "goblin-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
goblin_lexer = { package = "goblin-lexer", path = "../goblin-lexer" }
goblin-diagnostics = { path = "../goblin-diagnostics" }
goblin-parser = { path = "../goblin-parser" } 

