[workspace]
members = [
    "crates/goblin-source",
    "crates/goblin-diagnostics",
    "crates/goblin-lexer",
    "crates/goblin-ast",
    "crates/goblin-parser",
    "crates/goblin-interpreter",
    "crates/goblin-cli", "crates/goblin-gql",
    "crates/goblin-gql",
]
resolver = "2"
