[package]
name = "goblin-lexer"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[lib]
name = "goblin_lexer"
path = "src/lib.rs"

[dependencies]
chumsky = "0.9"
goblin_diagnostics = { package = "goblin-diagnostics", path = "../goblin-diagnostics" }
