[package]
name = "goblin-interpreter"
version = "0.28.0"
edition = "2024"

[lib]
name = "goblin_interpreter"
path = "src/lib.rs"

[dependencies]
goblin-ast = { path = "../goblin-ast" }
goblin-diagnostics = { path = "../goblin-diagnostics" }
goblin-lexer = { path = "../goblin-lexer" }
goblin-parser = { path = "../goblin-parser" }
goblin-yall = { path = "../goblin-yall" }
serde = { version = "1", features = ["derive"] }
uuid = { version = "1", features = ["v4", "v7", "serde", "fast-rng"] }
serde_json = "1"
serde_yaml = "0.9.33"
rust_decimal = { version = "1", features = ["serde"] }  # base; maths is gated by feature below
walkdir = "2"
regex = "1.8.1"
comrak = "0.21"
syntect = { version = "5", default-features = false, features = ["default-syntaxes", "default-themes", "html", "yaml-load"] }
dunce = "1"
indexmap = "2"

[features]
# Enabling "maths" here also enables rust_decimal's maths feature
maths = ["rust_decimal/maths"]

# No default features — you opt-in
default = []
