[package]
name = "goblin-parser"
version = "0.1.0"
edition = "2024"

[dependencies]
goblin-ast          = { path = "../goblin-ast" }
goblin-lexer        = { path = "../goblin-lexer" }
goblin-diagnostics  = { path = "../goblin-diagnostics" }
