[package]
name = "goblin-gql"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Goblin Query Language (Grvyrd DSL) parser and AST"
repository = "https://github.com/ddonche/goblin-lang" # optional

[lib]
path = "src/lib.rs"

[dependencies]
